import { startApp } from "./lib";
import Container from "typedi";
import { SessionService } from "./services";

import {
  ArticleApiController,
  HomeController,
  ProductApiController,
  ProductCategoryApiController,
  SessionApiController,
  UserApiController,
  UploadApiController,
  AvPostApiController,
  ProductOnXianOnSaleApiController,
  ProductOffXianOffSaleApiController,
  ProductOnXianBannedApiController,
  SettingApiController,
  AvStarApiController,
  AvCategoryApiController,
  ArticleCategoryApiController,
  AvTagApiController,
  AvPostCommentApiController,
  ChatMsgApiController,
  GptChatApiController,
  DeviceGptChatsController,
  NotificationApiController,
  GlobalChatMessageApiController,
  LinePostApiController,
} from "./controllers";
import {
  MyFriendApplyController,
  MyFriendshipController,
  UserAvPostCommentsController,
  UserGptChatCommentsController,
  UserGptChatsController,
  UserNotificationController,
  UserUserAvPostLikesController,
} from "./controllers/api/users";
import { GptChatCommentApiController } from "./controllers/api/gpt.chat.comment.api.controller";
import { UserUserGptChatLikesController } from "./controllers/api/users/user.gpt.chat.like";
import { UserApplyApiController } from "./controllers/api/user.apply.api.controller";

startApp({
  apiControllers: [
    ArticleApiController,
    HomeController,
    SessionApiController,
    UserApiController,
    ProductApiController,
    ProductCategoryApiController,
    UploadApiController,
    AvPostApiController,
    AvStarApiController,
    ArticleCategoryApiController,
    ProductOnXianOnSaleApiController,
    ProductOffXianOffSaleApiController,
    ProductOnXianBannedApiController,
    SettingApiController,
    AvCategoryApiController,
    AvTagApiController,
    AvPostCommentApiController,
    UserAvPostCommentsController,
    UserUserAvPostLikesController,
    ChatMsgApiController,
    GptChatApiController,
    UserGptChatsController,
    UserGptChatCommentsController,
    GptChatCommentApiController,
    UserUserGptChatLikesController,
    DeviceGptChatsController,
    UserApplyApiController,
    NotificationApiController,
    UserNotificationController,
    MyFriendApplyController,
    GlobalChatMessageApiController,
    MyFriendshipController,
    LinePostApiController,
  ],
  pageControllers: [],
  jwtValidation: Container.get(SessionService).validate,
});
